name: cf
channels:
  - conda-forge
  - nodefaults
dependencies:
  - anaconda-client
  - python=3.8
  - requests
  - conda-smithy
  - pygithub
  - pydantic
#  - cirun
#  - conda-smithy
# TEMP Remove pip install after testing
  - pip:
    - git+https://github.com/jaimergp/conda-smithy.git@gha-self-hosted-cirun
    - git+https://github.com/aktechlabs/cirun-py.git@main
