name: cf
channels:
  - conda-forge
  - nodefaults
dependencies:
  - anaconda-client
  - python=3.8
  - requests
  - conda-smithy
  - pygithub
  - pydantic
  - cirun
  - conda-smithy
  - pip:
      - git+https://github.com/isuruf/conda-smithy.git@without-all
