name: check
on:
  pull_request:
    branches:
      - main

env:
  PYTHONUNBUFFERED: 1

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: cf
        environment-file: environment.yml
        auto-activate-base: true
        miniforge-version: latest
        miniforge-variant: Mambaforge

    - name: Check packages exist on main (or label/broken)
      shell: bash -el {0}
      run: |
          test -f broken/example.txt
          test -f unbroken/example.txt
          conda activate cf
          python mark_broken.py check

    - name: Check feedstocks exist for token reset
      shell: bash -el {0}
      run: |
          test -f token_reset/example.txt
          conda activate cf
          python token_reset.py check

    - name: Check feedstocks can be (un)archived
      shell: bash -el {0}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          test -f archive/example.txt
          test -f unarchive/example.txt
          conda activate cf
          python archive_feedstock.py check
